FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt
RUN sudo apt-add-repository ppa:ansible/ansible
RUN sudo apt update
sudo apt install ansible

COPY . .

CMD [ "python", "./your-daemon-or-script.py" ]