FROM python:3

WORKDIR /usr/src/app

#recordar que req py pip van juntos
#COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt

RUN sudo apt-add-repository ppa:ansible/ansible
RUN sudo apt update
RUN sudo apt install ansible

#Aca poner la lista de hosts
COPY . . 
df -
CMD [ "python", "./your-daemon-or-script.py" ]